  language: python
  python:
    - "2.7"
    - "3.6"
  install:
    - pip install --upgrade -r requirements-dev.txt
    - pip install --upgrade --editable .
  script:
    - py.test --cov ./stone_burner --cov ./tests --doctest-modules --verbose ./stone_burner ./tests
